### ISSUE TITLE
Update the support libraries, gradle plugin and kotlin version

### ISSUE THREAD

**Issue by erdo** [erdo/android-fore#18]
Make sure nothing breaks (run all the sample app tests)

**Comment by erdo** [comment]
Please go ahead! :) I'll try not to leave it too long in code review

**Comment by erdo** [comment]
@nishant-nimbare are you still interested in this? I might take a look at it on Sunday if not :)

**Comment by nishant-nimbare** [comment]
Sorry . I am currently having my exams , won't be able to do it. Sorry once again

**Comment by erdo** [comment]
np ;) good luck with the exams
